on:
    push:
      branches: [ master-pipeline ]
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v3.2.0
          with:
                dotnet-version: 7.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test
        - name: Publish
          run: dotnet publish ./RestuarantAPI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
          
          
    deploy-dev:
        runs-on: ubuntu-latest
        needs: build
        steps:
    