on:
    push:
      branches: [ master-pipeline ]
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v3.2.0
          with:
                dotnet-version: 7.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test
        - name: Publish
          run: dotnet publish ./RestuarantAPI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
        - name: Upload Artifact
          uses: actions/upload-artifact@v3.1.3
          with: 
            name: api-artifact
            path: ${{ env.DOTNET_ROOT }}/api  
          
    deploy-dev:
        runs-on: ubuntu-latest
        needs: build
        environment: 
            name: 'Dev'
            url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
        steps: 
            - name: Download a Build Artifact
              uses: actions/download-artifact@v2.1.1
              with:
                  name: api-artifact
            - name: Azure WebApp Deploy
              id: deploy-to-azure
              uses: Azure/webapps-deploy@v2.2.11
              with:
                  app-name: 'bc-restaurant-api-app'
                  publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
